name: Node Angular Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v3

      # 2️⃣ Installer Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances depuis la racine
      - name: Install dependencies
        run: npm install

      # 4️⃣ Lancer les tests unitaires (si tu en as)
      - name: Run tests
        run: npm test || echo "No tests, continue"

      # 5️⃣ Build Angular ou Node
      - name: Build app
        run: npm run build || echo "No build script, continue"

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t mon_app_devops -f docker/Dockerfile .

      # 7️⃣ Test Docker image (optionnel)
      - name: Test Docker image
        run: docker run --rm mon_app_devops
